version: '3.8'

services:
  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: symfony_ddd
      MYSQL_USER: app
      MYSQL_PASSWORD: example
    ports:
      - "33066:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  database_test:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: soil_v3_test
      MYSQL_USER: app
      MYSQL_PASSWORD: example
    ports:
      - "33067:3306"

volumes:
  mariadb_data: 