version: '3.8'

services:
  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: notification_service
      MYSQL_USER: app
      MYSQL_PASSWORD: example
    ports:
      - "33068:3306"
    volumes:
      - notification_db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  notification_db_data: 